GEMINI_API_KEY="AIzaSyAVbXd__UuSvwreeNUZBcE2TjQPbbyxvsQ"
OPENAI_API_KEY="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"
